import requests

from config import base_url, api_version, API_KEY


def scan_url(url_to_scan):
    """
    @summary: Scans and checks url for malicious content
    :param: url_to_scan
    :return: response
    """
    _url = f"{base_url}/{api_version}/urls"
    payload = {"url": url_to_scan}
    headers = {
        "accept": "application/json",
        "x-apikey": API_KEY,
        "content-type": "application/x-www-form-urlencoded"
    }
    response = requests.post(_url, data=payload, headers=headers)
    json_resp = response.json()
    if response.status_code != 200:
        raise Exception(f"Scan failed code: {response.status_code} "
                        f"message: '{json_resp.get('error').get('message')}'")
    return json_resp


def get_url_analysis_report(url_id):
    """
    @summary: Get url analysis report
    :param url_id: URL identifiers generated by get_url_scan_analysis()
                   or generate_url_identifier()
    :return: report response
    """
    _url = f"{base_url}/{api_version}/urls/{url_id}"
    headers = {
        "accept": "application/json",
        "X-Apikey": API_KEY,
    }
    response = requests.get(_url, headers=headers)
    json_resp = response.json()
    if response.status_code != 200:
        raise Exception(f"Analysis report failed code: {response.status_code} "
                        f"message: '{json_resp.get('error').get('message')}'")
    return json_resp
